Maude updated to alpha115

diff --git a/tests/Misc/smtTest b/tests/Misc/smtTest
--- a/tests/Misc/smtTest
+++ b/tests/Misc/smtTest
@@ -1,5 +1,17 @@
 #!/bin/sh
 
+if grep "#define USE_CVC4" ../../config.h ; # are we using CVC4?
+then
+  echo "testing CVC4"
+else if grep "#define USE_YICES2" ../../config.h ; # are we using YICES2?
+then
+  echo "testing Yices2"
+else
+  echo "no SMT support compiled in"
+  exit 77 # grep returned nonzero exit so skip this test
+fi
+fi
+
 MAUDE_LIB=$srcdir/../../src/Main
 export MAUDE_LIB
 
